name: Run Updater Script
on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 10 minutes
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install useragenter requests bs4 colorthon requests-random-user-agent
    
    - name: Download Script New Version
      run: curl -L ${{ secrets.GIT_SCRIPT }} -o script.py

    - name: Permisioner Files
      run: chmod +x script.py&&python script.py
      
    - name: Run Remover Py Updater
      run: rm -r *.py

    - name: Commit and Push Changes
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git pull
        git add -A
        git commit -m "Update And Add Markdown Pages"
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_SCRIPT: ${{ secrets.GIT_SCRIPT }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
