name: Run Updater Script

on:
  schedule:
    # Runs at every 30th minute past the hour
    - cron: '*/30 * * * *'
  workflow_dispatch:
     inputs:
       logLevel:
         description: Runner Logs Mode
         required: true
         default: Runner
         type: choice
         options:
           - Runner
           - Runner3x
           - Runner6x

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main  # Explicitly check out the main branch

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 colorthon requests_random_user_agent

    - name: Download script
      run: curl -o news_grabber.py ${{ secrets.GIT_SCRIPT }}

    - name: Run script
      run: python news_grabber.py
  
    - name: Remove Python Script
      run: rm -r news_grabber.py

    - name: Commit changes
      run: |
        git config --global user.name '${{ secrets.GIT_NAME }}'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'
        git add .
        git commit -m "Auto-update news at $(date +'%Y-%m-%d %H:%M:%S')"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: main  # Specify the branch to push changes to

      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_SCRIPT: ${{ secrets.GIT_SCRIPT }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
